### ISSUE TITLE
Storage permissions not in book

### ISSUE THREAD

**Issue by ctownshend** [jameshibbard/dad-joke-chrome-extension#1]
Hi you do not have a section in the book where you tell people to add the storage permissions
` "permissions": [
    "storage"
  ]`

you need that to allow for logJokes capability

**Comment by jameshibbard** [comment]
Thanks for that. It's been a while since I wrote that, but it very much sounds like you are correct.
I'll have a look into it in the next day or so and get things updated accordingly.

**Comment by jameshibbard** [comment]
I just added a couple of lines telling people to add `"permissions": [ "storage" ]` to the manifest file, so as to give the extension access to the `chrome.storage` API. The minibook should be updated in the next couple of days. Thanks again.
